config/routes.rb
Rails.application.routes.draw do
  resources :products do
    collection do
      get :export
    end
  end
  
  resources :exporters, only: [:show]
  namespace :api do
    namespace :v1 do
      resources :async_jobs, only: [:show]
    end
  end
  root 'products#index'
end

app/models/async_job.rb
class AsyncJob < ActiveRecord::Base
end

app/models/exporter.rb
class Exporter < ActiveRecord::Base
  mount_uploader :file, ExporterUploader
end

app/models/product.rb
class Product < ActiveRecord::Base
  def percentage
    "#{self.rate * self.quantity / 100}%"
  end

  def total
    self.quantity + self.price
  end

  def otro
    self.total * self.rate
  end
end

app/controllers/api/v1/async_jobs_controller.rb
class Api::V1::AsyncJobsController < ApplicationController
  def show
    @job = AsyncJob.find(params[:id])
    render json: @job
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exporters_controller.rb
class ExportersController < ApplicationController
  def show
    @job_id = params[:id] 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    respond_to do |format|
      format.html do  
        @products = Product.all.page(params[:page]).per(100)
      end
      format.json
      format.xlsx do
        @products = Product.all
        @job = AsyncJob.create({title: "Exporting csv", progress: 0, total: @products.count})
        exporter = Exporter.new
        exporter.file = Pathname.new('public/system/export.csv').open
        exporter.save
        ProductsExcporterJob.perform_async(@job.id, @products, exporter)
        redirect_to exporter_path(@job)
      end
    end
  end

  def show
  end
  
  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :quantity, :rate)
    end
end

app/helpers/api/v1/async_jobs_helper.rb
module Api::V1::AsyncJobsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exporters_helper.rb
module ExportersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/exporters/show.html.haml
%center
  .progress-section
    %h3 
      Progreso
      %span.job-progress
        0%
    .progress
      .progress-bar.progress-bar-success.progress-bar-striped{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "40", :role => "progres    sbar", :style => "width:0%"}

  .download-section.hidden
    %h3
      Descargar Archivo

    = link_to 'View csv', Exporter.last.file.url, class: 'btn btn-success'

:javascript
  $(document).on('turbolinks:load', function(){
    var interval = setInterval(function(){
      $.get("/api/v1/async_jobs/#{@job_id}")
      .done(function(job){
        var progress = parseInt((job.progress * 100) / job.total);
        $('.job-progress').html(progress + '%');
        $('.progress-bar').css('width', progress + '%');
      })
      .fail(clean)
    }, 1000);

    function clean() {
      clearInterval(interval);
      $('.progress-section').addClass('hidden');
      $('.download-section').removeClass('hidden');
    }
  });
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BackgroundJob</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :rate
    = f.number_field :rate
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products
= link_to "export excel", products_path(format: :xlsx)
/%button{onclick: "downloadFile('#{export_products_path}.xlsx');"}
/Descargar
%table
  %thead
    %tr
      %th Id
      %th Name
      %th Description
      %th Price
      %th Quantity
      %th Rate
      %th Percentage
      %th total
      %th otro
      %th
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= product.id
        %td= product.name
        %td= product.description
        %td= product.price
        %td= product.quantity
        %td= product.rate
        %td= product.percentage
        %td= product.total
        %td= product.otro
        %td= link_to 'Show', product
        %td= link_to 'Edit', edit_product_path(product)
        %td= link_to 'Destroy', product, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_product_path

:javascript

   function downloadFile(urlToSend) {
        var req = new XMLHttpRequest();
             req.open("GET", urlToSend, true);
                  req.responseType = "blob";
                       req.onload = function (event) {
                                var blob = req.response;
                                         var fileName = req.getResponseHeader("fileName") //if you have the fileName header available
                                                  var link=document.createElement('a');
                                                           link.href=window.URL.createObjectURL(blob);
                                                                    link.download=fileName;
                                                                             link.click();
                                                                                  };

                                                                                       req.send();
                                                                                        }

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Description:
  = @product.description
%p
  %b Price:
  = @product.price
%p
  %b Quantity:
  = @product.quantity
%p
  %b Rate:
  = @product.rate

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path